//! Config-sweep differential test: ArKan vs PyTorch reference across multiple training configs.
//!
//! Each config covers one dimension of the sweep:
//!   - Optimizer: SGD, Adam
//!   - Spline order: 3, 4
//!   - Loss: MSE, BCE-with-logits
//!   - Depth: single-hidden (2→8→1), multi-hidden (2→8→8→1)
//!   - Backend: CPU (all tests), GPU (gated #[ignore])
//!
//! HONESTY RULES (strictly enforced):
//!   - If Layer 1 fails → weight bridge or forward bug. STOP.
//!   - If Layer 2 fails → gradient bug. STOP.
//!   - If Layer 3 diverges → report step + localization. Do NOT loosen tolerances.
//!
//! Run CPU sweep:  cargo test --test reference_parity_sweep -- --nocapture
//! Run GPU tests:  cargo test --features gpu --test reference_parity_sweep -- --ignored --nocapture
//!
//! JSON files are generated by scripts/export_training_reference.py.

use arkan::loss::masked_bce_with_logits;
use arkan::optimizer::Optimizer;
use arkan::{Adam, AdamConfig, KanConfig, KanNetwork};
use serde::Deserialize;
use std::fs;
use std::path::Path;

// ---------------------------------------------------------------------------
// JSON schema — matches export_training_reference.py
// ---------------------------------------------------------------------------

#[derive(Deserialize, Debug)]
struct RefConfig {
    input_dim: usize,
    hidden_dims: Vec<usize>,
    output_dim: usize,
    grid_size: usize,
    spline_order: usize,
    grid_range: (f32, f32),
    #[allow(dead_code)]
    global_basis_size: usize,
    #[allow(dead_code)]
    dims: Vec<usize>,
}

#[derive(Deserialize, Debug)]
struct LayerWeights {
    weights: Vec<f32>,
    bias: Vec<f32>,
}

#[derive(Deserialize, Debug)]
struct Dataset {
    inputs: Vec<f32>,
    targets: Vec<f32>,
    n_samples: usize,
}

#[derive(Deserialize, Debug)]
struct OptimizerConfig {
    #[serde(rename = "type")]
    opt_type: String,
    lr: f32,
    // SGD fields (optional). Parsed so the struct mirrors the exported JSON
    // schema; the sweep only drives Adam today, so nothing reads it.
    #[allow(dead_code)]
    momentum: Option<f32>,
    // Adam fields (optional)
    beta1: Option<f32>,
    beta2: Option<f32>,
    epsilon: Option<f32>,
    weight_decay: Option<f32>,
}

#[derive(Deserialize, Debug)]
struct Reference {
    config: RefConfig,
    optimizer: OptimizerConfig,
    #[serde(default = "default_loss_type")]
    loss_type: String,
    dataset: Dataset,
    init_weights: Vec<LayerWeights>,
    step0_forward: Vec<f32>,
    step0_grads: Vec<LayerWeights>,
    loss_trajectory: Vec<f32>,
    final_weights: Vec<LayerWeights>,
}

fn default_loss_type() -> String {
    "mse".to_string()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn load_reference(filename: &str) -> Reference {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let path = Path::new(manifest_dir)
        .join("tests")
        .join("reference_data")
        .join(filename);

    let data =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("Could not read {:?}: {}", path, e));

    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Could not parse {}: {}", filename, e))
}

fn build_network_with_ref_weights(ref_data: &Reference) -> KanNetwork {
    let cfg = &ref_data.config;
    let config = KanConfig {
        input_dim: cfg.input_dim,
        output_dim: cfg.output_dim,
        hidden_dims: cfg.hidden_dims.clone(),
        grid_size: cfg.grid_size,
        spline_order: cfg.spline_order,
        grid_range: cfg.grid_range,
        input_mean: vec![0.0f32; cfg.input_dim],
        input_std: vec![1.0f32; cfg.input_dim],
        multithreading_threshold: 128,
        simd_width: 8,
        init_seed: None,
    };
    let mut network = KanNetwork::new(config);

    assert_eq!(
        network.layers.len(),
        ref_data.init_weights.len(),
        "Layer count mismatch"
    );

    for (layer_idx, ref_layer) in ref_data.init_weights.iter().enumerate() {
        let layer = &mut network.layers[layer_idx];
        assert_eq!(
            ref_layer.weights.len(),
            layer.weights.len(),
            "Layer {layer_idx} weight count mismatch"
        );
        assert_eq!(
            ref_layer.bias.len(),
            layer.bias.len(),
            "Layer {layer_idx} bias count mismatch"
        );
        layer.weights.copy_from_slice(&ref_layer.weights);
        layer.bias.copy_from_slice(&ref_layer.bias);
    }
    network
}

fn max_abs_err(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn arkan_forward(network: &KanNetwork, dataset: &Dataset) -> Vec<f32> {
    let n = dataset.n_samples;
    let out_dim = network.config.output_dim;
    let mut workspace = network.create_workspace(n);
    let mut outputs = vec![0.0f32; n * out_dim];
    network.forward_batch(&dataset.inputs, &mut outputs, &mut workspace);
    outputs
}

/// Compute loss value and output gradient exactly matching ArKan's internals.
///
/// For MSE: grad[i] = 2*(pred-target)/N  (matches compute_masked_mse_loss_into)
/// For BCE: uses arkan::masked_bce_with_logits which matches PyTorch's
///          binary_cross_entropy_with_logits.
fn compute_loss_and_grad(predictions: &[f32], targets: &[f32], loss_type: &str) -> (f32, Vec<f32>) {
    match loss_type {
        "mse" => {
            let n = predictions.len() as f32;
            let mut loss = 0.0f32;
            let mut grad = vec![0.0f32; predictions.len()];
            for (i, (p, t)) in predictions.iter().zip(targets.iter()).enumerate() {
                let diff = p - t;
                loss += diff * diff;
                grad[i] = 2.0 * diff;
            }
            let inv = 1.0 / n;
            loss *= inv;
            for g in &mut grad {
                *g *= inv;
            }
            (loss, grad)
        }
        "bce" => masked_bce_with_logits(predictions, targets, None),
        _ => panic!("Unknown loss_type: {}", loss_type),
    }
}

/// Copy gradients only so the fixture comparison owns them independently of scratch.
fn run_backward(
    pass: arkan::training::ForwardPass<'_, '_>,
    grad_output: &[f32],
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>) {
    let gradients = pass.backward(grad_output).unwrap();
    (gradients.weights.to_vec(), gradients.biases.to_vec())
}

// ---------------------------------------------------------------------------
// Core 3-layer assertion helper
// ---------------------------------------------------------------------------

/// Asserts all 3 parity layers for a single config.
/// Returns (max_fwd_err, max_grad_err, max_traj_rel_err, pass).
/// On FAIL, panics with a diagnostic message.
fn assert_parity(config_name: &str, ref_data: &Reference) -> (f32, f32, f32) {
    let opt = &ref_data.optimizer;
    let loss_type = &ref_data.loss_type;
    println!(
        "\n=== [{config_name}] optimizer={}, order={}, loss={}, arch={:?} ===",
        opt.opt_type, ref_data.config.spline_order, loss_type, ref_data.config.dims
    );

    // -----------------------------------------------------------------------
    // LAYER 1: Forward parity
    // -----------------------------------------------------------------------
    let network = build_network_with_ref_weights(ref_data);
    let arkan_out = arkan_forward(&network, &ref_data.dataset);
    let max_fwd_err = max_abs_err(&arkan_out, &ref_data.step0_forward);
    println!(
        "[{config_name}][L1] Forward parity: max_abs_err = {:.2e}  (tol 1e-5)",
        max_fwd_err
    );

    assert!(
        max_fwd_err < 1e-5,
        "[{config_name}][L1 FAIL] Forward parity failed: max_err={:.4e} > 1e-5\n\
         Weight bridge or forward-pass bug.\n\
         ArKan[:5]  = {:?}\n\
         PyTorch[:5] = {:?}",
        max_fwd_err,
        &arkan_out[..arkan_out.len().min(5)],
        &ref_data.step0_forward[..ref_data.step0_forward.len().min(5)],
    );
    println!("[{config_name}][L1] PASS");

    // -----------------------------------------------------------------------
    // LAYER 2: Gradient parity
    // -----------------------------------------------------------------------
    let network = build_network_with_ref_weights(ref_data);
    let n = ref_data.dataset.n_samples;
    let out_dim = network.config.output_dim;
    let mut workspace = network.create_workspace(n);

    let mut predictions = vec![0.0f32; n * out_dim];
    let pass = network
        .try_forward_for_backward(&ref_data.dataset.inputs, &mut predictions, &mut workspace)
        .unwrap();

    let (_, grad_output) =
        compute_loss_and_grad(&predictions, &ref_data.dataset.targets, loss_type);

    let (weight_grads, bias_grads) = run_backward(pass, &grad_output);

    let grad_tol = 1e-4f32;
    let mut max_w_err = 0.0f32;
    let mut max_b_err = 0.0f32;
    let mut all_pass = true;

    for (layer_idx, ref_grad) in ref_data.step0_grads.iter().enumerate() {
        let w_err = max_abs_err(&weight_grads[layer_idx], &ref_grad.weights);
        let b_err = max_abs_err(&bias_grads[layer_idx], &ref_grad.bias);
        max_w_err = max_w_err.max(w_err);
        max_b_err = max_b_err.max(b_err);
        println!(
            "[{config_name}][L2] Layer {layer_idx}: weight_grad err={:.2e}, bias_grad err={:.2e}",
            w_err, b_err
        );
        if w_err >= grad_tol || b_err >= grad_tol {
            eprintln!(
                "[{config_name}][L2 FAIL] Layer {layer_idx}: w_err={:.4e}, b_err={:.4e} >= tol {:.1e}",
                w_err, b_err, grad_tol
            );
            all_pass = false;
        }
    }

    let max_grad_err = max_w_err.max(max_b_err);
    println!(
        "[{config_name}][L2] Gradient parity: max_w_err={:.2e}, max_b_err={:.2e}  (tol 1e-4)",
        max_w_err, max_b_err
    );
    assert!(
        all_pass,
        "[{config_name}][L2 FAIL] Gradient parity failed. \
         Forward (L1) passed, so error is in gradient computation."
    );
    println!("[{config_name}][L2] PASS");

    // -----------------------------------------------------------------------
    // LAYER 3: Trajectory parity
    // -----------------------------------------------------------------------
    let mut network = build_network_with_ref_weights(ref_data);
    let n_steps = ref_data.loss_trajectory.len();
    let lr = opt.lr;
    let mut workspace = network.create_workspace(n);

    // Build optimizer state for Adam (SGD uses train_step directly)
    let mut adam_opt: Option<Adam> = match opt.opt_type.as_str() {
        "adam" => {
            let cfg = AdamConfig {
                lr,
                beta1: opt.beta1.unwrap_or(0.9),
                beta2: opt.beta2.unwrap_or(0.999),
                epsilon: opt.epsilon.unwrap_or(1e-8),
                weight_decay: opt.weight_decay.unwrap_or(0.0),
                ..AdamConfig::default()
            };
            Some(Adam::new(&network, cfg))
        }
        _ => None,
    };

    let rel_tol = 1e-3f32;
    let mut diverged_at: Option<usize> = None;
    let mut max_traj_rel_err = 0.0f32;

    for step in 0..n_steps {
        let arkan_loss = match opt.opt_type.as_str() {
            "sgd" => {
                // SGD+MSE: use train_step directly (handles backward + SGD update)
                if loss_type == "mse" {
                    network.train_step(
                        &ref_data.dataset.inputs,
                        &ref_data.dataset.targets,
                        None,
                        lr,
                        &mut workspace,
                    )
                } else {
                    // SGD+BCE: manual forward + BCE loss + backward + SGD update
                    let mut predictions = vec![0.0f32; n * out_dim];
                    let pass = network
                        .try_forward_for_backward(
                            &ref_data.dataset.inputs,
                            &mut predictions,
                            &mut workspace,
                        )
                        .unwrap();
                    let (loss, grad_out) =
                        compute_loss_and_grad(&predictions, &ref_data.dataset.targets, loss_type);
                    let (wg, bg) = run_backward(pass, &grad_out);
                    // SGD update: w -= lr * grad
                    for (layer_idx, layer) in network.layers.iter_mut().enumerate() {
                        for (w, g) in layer.weights.iter_mut().zip(wg[layer_idx].iter()) {
                            *w -= lr * g;
                        }
                        for (b, g) in layer.bias.iter_mut().zip(bg[layer_idx].iter()) {
                            *b -= lr * g;
                        }
                    }
                    loss
                }
            }
            "adam" => {
                // Adam: manual forward + loss + backward + Adam update
                let mut predictions = vec![0.0f32; n * out_dim];
                let pass = network
                    .try_forward_for_backward(
                        &ref_data.dataset.inputs,
                        &mut predictions,
                        &mut workspace,
                    )
                    .unwrap();
                let (loss, grad_out) =
                    compute_loss_and_grad(&predictions, &ref_data.dataset.targets, loss_type);
                let (wg, bg) = run_backward(pass, &grad_out);
                // Adam update
                adam_opt
                    .as_mut()
                    .unwrap()
                    .step(&mut network, &wg, &bg, None)
                    .unwrap();
                loss
            }
            other => panic!("[{config_name}] Unknown optimizer type: {other}"),
        };

        let ref_loss = ref_data.loss_trajectory[step];
        let rel_err = (arkan_loss - ref_loss).abs() / ref_loss.abs().max(1e-8);
        max_traj_rel_err = max_traj_rel_err.max(rel_err);

        if step < 5 || step % 10 == 0 {
            println!(
                "[{config_name}][L3] step {:3}: arkan={:.6}, ref={:.6}, rel_err={:.2e}",
                step, arkan_loss, ref_loss, rel_err
            );
        }

        if rel_err >= rel_tol && diverged_at.is_none() {
            diverged_at = Some(step);
            eprintln!(
                "[{config_name}][L3] DIVERGENCE at step {}: arkan={:.6}, ref={:.6}, rel_err={:.4e}",
                step, arkan_loss, ref_loss, rel_err
            );
        }
    }

    if let Some(div_step) = diverged_at {
        // Localization: compare final weights
        let mut max_w_diff = 0.0f32;
        for (li, ref_final) in ref_data.final_weights.iter().enumerate() {
            let w_err = max_abs_err(&network.layers[li].weights, &ref_final.weights);
            let b_err = max_abs_err(&network.layers[li].bias, &ref_final.bias);
            max_w_diff = max_w_diff.max(w_err).max(b_err);
            println!(
                "[{config_name}][L3] Final weight diff layer {li}: w={:.4e}, b={:.4e}",
                w_err, b_err
            );
        }
        panic!(
            "[{config_name}][L3 FAIL] Training trajectory diverged at step {}.\n\
             L1 (forward) and L2 (gradient) PASSED, so:\n\
             SUSPECT: optimizer update formula or loss gradient mismatch.\n\
             Config: optimizer={}, loss={}, spline_order={}.\n\
             max_traj_rel_err={:.4e}, max_final_weight_diff={:.4e}",
            div_step,
            opt.opt_type,
            loss_type,
            ref_data.config.spline_order,
            max_traj_rel_err,
            max_w_diff
        );
    }

    // Final weight comparison
    let w_tol = 1e-3f32;
    let mut max_final_err = 0.0f32;
    for (li, ref_final) in ref_data.final_weights.iter().enumerate() {
        let w_err = max_abs_err(&network.layers[li].weights, &ref_final.weights);
        let b_err = max_abs_err(&network.layers[li].bias, &ref_final.bias);
        max_final_err = max_final_err.max(w_err).max(b_err);
        println!(
            "[{config_name}][L3] Final weight diff layer {li}: w={:.4e}, b={:.4e}",
            w_err, b_err
        );
    }

    println!(
        "[{config_name}][L3] Trajectory PASS: max_traj_rel_err={:.2e}, max_final_weight_err={:.4e}",
        max_traj_rel_err, max_final_err
    );
    assert!(
        max_final_err < w_tol,
        "[{config_name}][L3 FAIL] Final weights diverged: max_err={:.4e} > {:.1e}",
        max_final_err,
        w_tol
    );
    println!("[{config_name}] ALL LAYERS PASS");

    (max_fwd_err, max_grad_err, max_traj_rel_err)
}

// ---------------------------------------------------------------------------
// CPU tests — one per config
// ---------------------------------------------------------------------------

#[test]
fn sweep_sgd_order3() {
    let ref_data = load_reference("training_ref_sgd_order3.json");
    assert_parity("sgd_order3", &ref_data);
}

#[test]
fn sweep_adam_order3() {
    let ref_data = load_reference("training_ref_adam_order3.json");
    assert_parity("adam_order3", &ref_data);
}

#[test]
fn sweep_sgd_order4() {
    let ref_data = load_reference("training_ref_sgd_order4.json");
    assert_parity("sgd_order4", &ref_data);
}

#[test]
fn sweep_bce_order3() {
    let ref_data = load_reference("training_ref_bce_order3.json");
    assert_parity("bce_order3", &ref_data);
}

#[test]
fn sweep_multilayer() {
    let ref_data = load_reference("training_ref_multilayer.json");
    assert_parity("multilayer", &ref_data);
}

// ---------------------------------------------------------------------------
// GPU tests — gated with #[ignore = "Requires GPU"]
// ---------------------------------------------------------------------------

/// GPU parity: build GpuNetwork from CPU reference weights, train via hybrid path
/// (GPU forward + CPU backward + CPU Adam + weight sync), compare to PyTorch CPU oracle.
///
/// Note: GpuNetwork::train_step_mse uses the hybrid approach with CPU Adam optimizer.
/// It no longer clips gradients by default (the previously hardcoded
/// max_grad_norm=Some(1.0) was removed; default is now None, matching the CPU path
/// and the unclipped PyTorch oracle). We use the Adam reference (same JSON) since the
/// GPU hybrid path uses Adam.
#[cfg(feature = "gpu")]
#[test]
#[ignore = "Requires GPU"]
fn sweep_gpu_adam_hybrid() {
    use arkan::gpu::{GpuNetwork, WgpuBackend, WgpuOptions};
    use arkan::{Adam, AdamConfig};

    // Use the Adam reference — GPU train_step_mse uses CPU Adam internally and
    // (since the hardcoded clip was removed) no longer clips gradients by default,
    // so it should track the unclipped PyTorch Adam oracle exactly.
    let ref_data = load_reference("training_ref_adam_order3.json");
    let config_name = "gpu_adam_hybrid";
    let opt = &ref_data.optimizer;
    let lr = opt.lr;

    println!(
        "\n=== [{config_name}] GPU hybrid (forward GPU + backward CPU Adam) order={} ===",
        ref_data.config.spline_order
    );

    let backend = WgpuBackend::init(WgpuOptions::default()).expect("Failed to create GPU backend");

    let cpu_network_init = build_network_with_ref_weights(&ref_data);

    // --- L1: GPU forward parity ---
    {
        let mut gpu_net =
            GpuNetwork::from_cpu(&backend, &cpu_network_init).expect("GpuNetwork::from_cpu failed");
        let n = ref_data.dataset.n_samples;
        let mut gpu_ws = gpu_net
            .create_workspace(n)
            .expect("create_workspace failed");
        let gpu_out = gpu_net
            .forward_batch(&ref_data.dataset.inputs, n, &mut gpu_ws)
            .expect("GPU forward failed");

        let fwd_err = max_abs_err(&gpu_out, &ref_data.step0_forward);
        println!(
            "[{config_name}][L1] GPU forward parity: max_err={:.2e}  (tol 1e-4)",
            fwd_err
        );
        assert!(
            fwd_err < 1e-4,
            "[{config_name}][L1 FAIL] GPU forward error {:.4e} > 1e-4\n\
             GPU forward path or GpuNetwork::from_cpu weight bridge is broken.",
            fwd_err
        );
        println!("[{config_name}][L1] PASS");
    }

    // --- L3: GPU hybrid Adam trajectory vs CPU PyTorch Adam oracle ---
    // IMPORTANT: train_step_mse applies max_grad_norm=Some(1.0) internally.
    // Our PyTorch oracle uses no clipping. To make a fair comparison, we test
    // whether the trajectories match the oracle — if they diverge, we report
    // the likely cause (the hardcoded clipping in train_step_mse).
    let n_steps = ref_data.loss_trajectory.len();
    let n = ref_data.dataset.n_samples;

    let mut gpu_net =
        GpuNetwork::from_cpu(&backend, &cpu_network_init).expect("GpuNetwork::from_cpu failed");
    let mut gpu_ws = gpu_net
        .create_workspace(n)
        .expect("create_workspace failed");
    let mut cpu_net_for_gpu = build_network_with_ref_weights(&ref_data);

    let adam_cfg = AdamConfig {
        lr,
        beta1: opt.beta1.unwrap_or(0.9),
        beta2: opt.beta2.unwrap_or(0.999),
        epsilon: opt.epsilon.unwrap_or(1e-8),
        weight_decay: opt.weight_decay.unwrap_or(0.0),
        ..AdamConfig::default()
    };
    let mut adam_cpu = Adam::new(&cpu_net_for_gpu, adam_cfg);

    // NOTE: train_step_mse applies Some(1.0) gradient clipping.
    // This differs from PyTorch oracle (no clipping), so trajectory MAY diverge.
    // We use rel_tol=5e-3 to check if clipping is actually impactful on this dataset.
    let rel_tol = 5e-3f32;
    let mut diverged_at: Option<usize> = None;
    let mut max_traj_rel_err = 0.0f32;

    for step in 0..n_steps {
        let arkan_loss = gpu_net
            .train_step_mse(
                &ref_data.dataset.inputs,
                &ref_data.dataset.targets,
                n,
                &mut gpu_ws,
                &mut adam_cpu,
                &mut cpu_net_for_gpu,
            )
            .expect("GPU hybrid Adam train_step_mse failed");

        let ref_loss = ref_data.loss_trajectory[step];
        let rel_err = (arkan_loss - ref_loss).abs() / ref_loss.abs().max(1e-8);
        max_traj_rel_err = max_traj_rel_err.max(rel_err);

        if step < 5 || step % 10 == 0 {
            println!(
                "[{config_name}][L3] step {:3}: gpu={:.6}, ref={:.6}, rel_err={:.2e}",
                step, arkan_loss, ref_loss, rel_err
            );
        }

        if rel_err >= rel_tol && diverged_at.is_none() {
            diverged_at = Some(step);
            eprintln!(
                "[{config_name}][L3] GPU DIVERGENCE at step {}: gpu={:.6}, ref={:.6}, rel_err={:.4e}",
                step, arkan_loss, ref_loss, rel_err
            );
        }
    }

    if let Some(div_step) = diverged_at {
        panic!(
            "[{config_name}][L3 FAIL] GPU hybrid Adam trajectory diverged at step {}.\n\
             train_step_mse no longer clips by default, so the GPU hybrid path should\n\
             match the unclipped PyTorch Adam oracle. A divergence here indicates a real\n\
             GPU training bug (forward/backward/optimizer), not gradient clipping.\n\
             max_traj_rel_err={:.4e} > {:.1e}",
            div_step, max_traj_rel_err, rel_tol
        );
    }

    println!(
        "[{config_name}][L3] GPU hybrid Adam Trajectory PASS: max_traj_rel_err={:.2e}",
        max_traj_rel_err
    );
    println!("[{config_name}] GPU hybrid ALL LAYERS PASS");
}
